builds:
  - id: deps
    main: ./cmds/deps/main.go
    binary: deps
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

brews:
  - name: depscloud-cli
    goarm: 7
    github:
      owner: deps-cloud
      name: homebrew-tap
    download_strategy: CurlDownloadStrategy.
    commit_author:
      name: goreleaserbot
      email: mjpitz@deps.cloud
    homepage: https://deps.cloud/
    description: Command line interface to the deps.cloud API.

nfpms:
  - id: depscloud-cli-deb
    package_name: depscloud-cli
    builds:
      - deps
    vendor: deps.cloud
    homepage: https://deps.cloud/
    description: Command line interface to the deps.cloud API.
    license: MIT
    formats:
      - deb

publishers:
  - name: deps
    ids:
      - depscloud-cli-deb
    cmd: |
      curl -F package=@{{ .ArtifactPath }} https://${TOKEN}@push.fury.io/deps-cloud/
    env:
      - TOKEN={{ .Env.GEMFURY_TOKEN }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
