name: tag

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: golang:1.14-alpine3.11
    steps:
      - name: Prepare
        run: apk -U upgrade && apk add build-base git ca-certificates curl

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        env:
          GEMFURY_TOKEN: ${{ secrets.GEMFURY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
        run: |
          curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
          make build-deps deps test
          ./bin/goreleaser
          find dist/ -iname *.deb | xargs -I{} curl -F package=@{} https://${GEMFURY_TOKEN}@push.fury.io/depscloud/
